### ISSUE TITLE
please tag 2.8.0

### ISSUE THREAD

**Issue by stefantalpalaru** [mean00/avidemux2_i18n#19]
Gentoo ebuilds, and probably other packages, assume this repo's releases are in sync with https://github.com/mean00/avidemux2

It would help packagers to keep them in sync.

**Comment by eumagga0x2a** [comment]
For the sake of users, distributors should consider either using [the support_2.8.0 branch](https://github.com/mean00/avidemux2/commits/support_2.8.0) rather than the tagged release for their Avidemux packages or applying the patches from there atop of the 2.8.0 release.

If it helps even a little bit, I could apply https://github.com/mean00/avidemux2/commit/c055d72474dc36de822017e0d3a58343fddb1403 to the branch to include updated French and Japanese translations while remaining compatible with the 2.8.0 release. The purpose of moving translations to a separate repo was to make it easier to ship updated translations later. I'll branch prior to refreshing translation files again, but right now, the master is fully usable with the 2.8.0 release and with the support_2.8.0 branch.

I am very sorry for the inconvenience.
